# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_Code',
            field=models.FloatField(max_length=6),
        ),
    ]
