# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='farm_Type',
            field=models.IntegerField(choices=[(1, 'Commercial'), (2, 'Family'), (3, 'Recreational'), (4, 'Other')]),
        ),
    ]
